name: phibus
favicon: null
layout_spectrum: 0.9136684299446642
typography_spectrum: 0.531894744373858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4965975165832788
  lightness: 0.4705812786705792
  saturation: 0.06608085124753416
  rhythmicContrast: 0.4385038123000413
purpose: []
